### ISSUE TITLE
Conflict between LungJ and GDSC update sites

### ISSUE THREAD

**Issue by tferr** [LWollatz/LungJ#2]
@LWollatz, @aherbert, 

When looking at redundancies between the BAR update site and other update sites on http://sites.imagej.net/, I noticed the following:
The LungJ and GDSC update sites both feature a "Apply Mask" command. Because in IJ1 commands must be unique, users are prompted with a `Plugin configuration error` at startup.
You can reproduce this by subscribing to both update sites. 

AFAICT, the options to address this would be:

1. Rename one of the offending commands (appending an underscore or a space, would suffice)
2. Since this is simply an IJ1 restriction, one could write an IJ2 command wrapper that calls the class implementing the offending command, using, e.g., [this example](https://github.com/imagej/imagej-tutorials/blob/master/simple-commands/src/main/java/HelloWorld.java)

Does this make sense?

**Comment by LWollatz** [comment]
Don't know what GDSC refers to, so I don't know what that"Apply Mask" function does, but I get what you mean. Can think of a different name, i.e. "Apply Mask to Image". Makes it longer, but that should be ok. The actual function names do not need to be unique, just the menu entries, am I right?

**Comment by LWollatz** [comment]
P.S.: I am not a big fan of just appending an underscore or a space, as I think this is confusing for the end user as the two functions would be seemingly the same. But might still do that.

**Comment by imagejan** [comment]
GDSC = Genome Damage and Stability Centre, see [here](http://www.sussex.ac.uk/gdsc/intranet/microscopy/imagej/gdsc_plugins) and the [update site](http://sites.imagej.net/GDSC/).

Here's the source:
https://github.com/aherbert/GDSC/blob/83fa71a/src/main/resources/gdsc/plugins.config#L62
https://github.com/aherbert/GDSC/blob/master/src/main/java/gdsc/threshold/ApplyMask.java

@aherbert might also want to comment on this.

IMHO, this is such a basic functionality, it should live in ImageJ or Fiji to avoid any code redundancies (and inconsistencies).

**Comment by LWollatz** [comment]
Thanks, found it and went through the code. Looks like the general aim of the two functions is the same. GDSC is giving more options so I could rename mine to "Apply Mask (Simple)". :-)

**Comment by aherbert** [comment]
This is always going to be a problem with the plugin architecture of  ImageJ. The more plugins you add the more chance of a name clash. 

In the past I have just renamed commands to avoid the conflict when I was aware of it. If @LWollatz is prepared to rename their plugin then this will solve the issue. Otherwise I can rename mine.

**Comment by tferr** [comment]
What would be nice would be to e.g., have a shell script that goes through all of the jar files in http://sites.imagej.net/, parses their `plugins.config` files and checks for duplicated entries. Developers could run it to predict any problems before uploading their jars. This would be a nice way to start addressing some of the limitations of the current system (See also this [forum post](http://forum.imagej.net/t/customize-menus-in-fiji/2442?u=tferr)).
 Anyone wants to take on the task?
